# -*- coding: utf-8 -*-
"""RESUMO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qz5TIzJ6RXtLJZ3X_aXrh5P8YLg0bEzI
"""

from sklearn.module import Model

model = Model()

model.fit(X, y)

predictions = model.predict(X_new)

print(predictions)